package org.study.entities;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.ToString;

@Data
@ToString
@DynamoDBTable(tableName = "Student")
public class Student {

    @DynamoDBHashKey(attributeName = "studentId")
    @DynamoDBAutoGeneratedKey
    private String studentId;
    @DynamoDBRangeKey
    private String lastName;
    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private int age;
    @DynamoDBAttribute
    private Address address;
}
